src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Fullname = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }


    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullname(): ?string
    {
        return $this->Fullname;
    }

    public function setFullname(string $Fullname): static
    {
        $this->Fullname = $Fullname;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }


}

templates/PrivatePage/PrivatePage.html.twig
{% extends 'heritage/heritage.html.twig' %}
{% block Title %}Home{% endblock %}

{% block path1 %}
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ path('PrivatePage') }}">Home</a></li>
{% endblock %}
{% block path2 %}
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ path('createcampaign') }}">Create Campaign</a></li>
{% endblock %}
{% block path3 %}
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ path('Profile_Page') }}">Profile </a></li>
{% endblock %}
{% block path4 %}
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ path('app_logout') }}">Log out </a></li>
{% endblock %}


{% block HeaderDocument %}
        {% for message in app.session.flashBag.get('success') %}
      <div class="alert alert-success">
          {{ message }}
      </div>
  {% endfor %}

    {% for message in app.session.flashBag.get('campaign_success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

        {{ parent() }}
    {% endblock %}
{% block sectionDocument %}

<div class="container">
    <!-- Portfolio Section Heading-->
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Campaigns</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
    </div>
    <!-- Portfolio Grid Items-->
    <div class="row justify-content-center">
        {% for campaign in campaigns %}
        <div class="col-md-12 mb-5">
    <div class="border rounded p-3">
        <div class="row">
            <!-- Image Column -->
            <div class="col-md-6">
                <div class="campaign-image text-center mt-3">
                    <img class="img-fluid" src="assets/img/portfolio/{{ campaign.Image }}" alt="{{ campaign.Description }}" />
                </div>
            </div>
            <!-- Description and Button Column -->
            <div class="col-md-6">
                <div class="campaign-info mt-3">
                    <!-- Campaign Name and Description -->
                    <h3>{{ campaign.CampaignName }}</h3>
                    <p>{{ campaign.Description }}</p>
                    <!-- View Details Button -->
                    <button class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#portfolioModal{{ loop.index }}">
                        View Details
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

        <!-- Portfolio Modal -->
<div class="portfolio-modal modal fade" id="portfolioModal{{ loop.index }}" tabindex="-1" aria-labelledby="portfolioModal{{ loop.index }}" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header border-0">
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center pb-5">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <!-- Portfolio Modal - Title-->
                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">{{ campaign.CampaignName }}</h2>
                            <!-- Icon Divider-->
                            <div class="divider-custom">
                                <div class="divider-custom-line"></div>
                                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                <div class="divider-custom-line"></div>
                            </div>
                            <!-- Portfolio Modal - Image-->
                            <img class="img-fluid rounded mb-5" src="assets/img/portfolio/{{ campaign.Image }}" alt="Image Not Found" />
                            <!-- Portfolio Modal - Text-->
                            <p class="mb-4">{{ campaign.Description }}</p>
                            <!-- Budget and Owner Information -->
                            <p><strong>Budget:</strong> {{ campaign.Budget }} Dt</p>
                            <p><strong>Owner:</strong> {{ campaign.Ownerid.fullname }}</p>
                            <p><strong>ContactOwner:</strong> {{ campaign.Ownerid.email }}</p>
                            <!-- Fund Campaign Button -->
                            <button class="btn btn-primary" data-bs-dismiss="modal">
                                <a class="btn btn-primary" href="{{ path('FundCampaign', {'id': campaign.id}) }}">
                                    Fund Campaign
                                </a>
                            </button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

        {% endfor %}
    </div>
</div>
    {% if app.session.get('from_create_campaign') is defined and app.session.get('from_create_campaign') %}
        <div id="thank-you-modal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <p>Merci pour votre participation !</p>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script>

        var modal = document.getElementById("thank-you-modal");
        var span = document.getElementsByClassName("close")[0];
        span.onclick = function() {
            modal.style.display = "none";
        }
        window.onload = function() {
            modal.style.display = "block";
        }
    </script>
{% endblock %}
{% block aboutDocument %}
{% endblock %}
{% block formDocument %}{% endblock %}